import GlobalStyle from '@/styles/GlobalStyle';
import Header from '@/components/layout/Header';
import SessionProviderWrapper from '@/components/providers/SessionProviderWrapper';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
  session: any;
}

export default function RootLayout({ children, session }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <GlobalStyle />
        <SessionProviderWrapper session={session}>
          <Header />
          <main>{children}</main>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
