name: CI + Vercel Deploy

on:
  pull_request:
    branches: [main, development]     
  push:
    branches: [main, development]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: CI (Install → Prisma Generate → Build → Test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - run: yarn prisma generate
      - run: yarn type-check
        env: { NEXT_TELEMETRY_DISABLED: 1 }
      - run: yarn build
        env: { NEXT_TELEMETRY_DISABLED: 1 }
      - run: yarn test

  deploy-preview:
    name: Deploy Preview (development)
    needs: test
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -rf .vercel                     # nuke stale local link
      - run: npm i -g vercel@latest

      # (optional) one-time debug to verify scope & visibility
      - name: Debug Vercel auth
        run: |
          vercel whoami --token ${{ secrets.VERCEL_TOKEN }}
          vercel projects ls --scope ${{ secrets.VERCEL_ORG_ID }} --token ${{ secrets.VERCEL_TOKEN }} | head -n 20

      - name: Pull env (preview)
        run: vercel pull --yes --environment=preview \
               --scope ${{ secrets.VERCEL_ORG_ID }} \
               --project ${{ secrets.VERCEL_PROJECT_ID }} \
               --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build (preview)
        run: vercel build \
               --scope ${{ secrets.VERCEL_ORG_ID }} \
               --project ${{ secrets.VERCEL_PROJECT_ID }} \
               --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (preview)
        run: vercel deploy --prebuilt \
               --scope ${{ secrets.VERCEL_ORG_ID }} \
               --project ${{ secrets.VERCEL_PROJECT_ID }} \
               --token ${{ secrets.VERCEL_TOKEN }}

  deploy-production:
    name: Deploy Production (main)
    needs: test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rm -rf .vercel
      - run: npm i -g vercel@latest

      - name: Pull env (production)
        run: vercel pull --yes --environment=production \
               --scope ${{ secrets.VERCEL_ORG_ID }} \
               --project ${{ secrets.VERCEL_PROJECT_ID }} \
               --token ${{ secrets.VERCEL_TOKEN }}

      - name: Build (production)
        run: vercel build --prod \
               --scope ${{ secrets.VERCEL_ORG_ID }} \
               --project ${{ secrets.VERCEL_PROJECT_ID }} \
               --token ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy (production)
        run: vercel deploy --prebuilt --prod \
               --scope ${{ secrets.VERCEL_ORG_ID }} \
               --project ${{ secrets.VERCEL_PROJECT_ID }} \
               --token ${{ secrets.VERCEL_TOKEN }}
