name: CI

on:
  pull_request:
    branches: [main] # run on PRs to gate merges
  push:
    branches: [main] # optional: keeps CI green on main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: CI (Install → Prisma Generate → Build → Test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Generate Prisma Client
        run: yarn prisma generate

      - name: Type-check (TypeScript)
        run: yarn type-check
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Build Next.js
        run: yarn build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Run tests
        run: yarn test
